/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect;
import java.sql.*;
/**
 *
 * @author Casi
 */
public class Interfata extends javax.swing.JFrame {

    /**
     * Creates new form Interfata
     */
    public Interfata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_6b = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTextArea();
        Button_3a = new javax.swing.JButton();
        Button_3b = new javax.swing.JButton();
        Button_4a = new javax.swing.JButton();
        Button_4b = new javax.swing.JButton();
        Button_5a = new javax.swing.JButton();
        Button_5b = new javax.swing.JButton();
        Button_6a = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        Size = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bilet9_Campean_Casiana");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_6b.setBackground(new java.awt.Color(255, 255, 204));
        Button_6b.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Button_6b.setForeground(new java.awt.Color(123, 0, 0));
        Button_6b.setText("Ex_6b");
        Button_6b.setBorder(null);
        Button_6b.setBorderPainted(false);
        Button_6b.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_6b.setMaximumSize(new java.awt.Dimension(71, 35));
        Button_6b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_6bActionPerformed(evt);
            }
        });
        getContentPane().add(Button_6b, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 120, 60));

        Tabel.setBackground(new java.awt.Color(255, 255, 204));
        Tabel.setColumns(20);
        Tabel.setForeground(new java.awt.Color(123, 0, 0));
        Tabel.setRows(5);
        Tabel.setToolTipText("");
        jScrollPane1.setViewportView(Tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 748, 270));

        Button_3a.setBackground(new java.awt.Color(255, 255, 204));
        Button_3a.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Button_3a.setForeground(new java.awt.Color(123, 0, 0));
        Button_3a.setText("Ex_3a");
        Button_3a.setBorder(null);
        Button_3a.setBorderPainted(false);
        Button_3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3aActionPerformed(evt);
            }
        });
        getContentPane().add(Button_3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, 60));

        Button_3b.setBackground(new java.awt.Color(255, 255, 204));
        Button_3b.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Button_3b.setForeground(new java.awt.Color(123, 0, 0));
        Button_3b.setText("Ex_3b");
        Button_3b.setBorder(null);
        Button_3b.setBorderPainted(false);
        Button_3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3bActionPerformed(evt);
            }
        });
        getContentPane().add(Button_3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 120, 60));

        Button_4a.setBackground(new java.awt.Color(255, 255, 204));
        Button_4a.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Button_4a.setForeground(new java.awt.Color(123, 0, 0));
        Button_4a.setText("Ex_4a");
        Button_4a.setBorder(null);
        Button_4a.setBorderPainted(false);
        Button_4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_4aActionPerformed(evt);
            }
        });
        getContentPane().add(Button_4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, 60));

        Button_4b.setBackground(new java.awt.Color(255, 255, 204));
        Button_4b.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Button_4b.setForeground(new java.awt.Color(123, 0, 0));
        Button_4b.setText("Ex_4b");
        Button_4b.setBorder(null);
        Button_4b.setBorderPainted(false);
        Button_4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_4bActionPerformed(evt);
            }
        });
        getContentPane().add(Button_4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 120, 60));

        Button_5a.setBackground(new java.awt.Color(255, 255, 204));
        Button_5a.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Button_5a.setForeground(new java.awt.Color(123, 0, 0));
        Button_5a.setText("Ex_5a");
        Button_5a.setBorder(null);
        Button_5a.setBorderPainted(false);
        Button_5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_5aActionPerformed(evt);
            }
        });
        getContentPane().add(Button_5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 120, 60));

        Button_5b.setBackground(new java.awt.Color(255, 255, 204));
        Button_5b.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Button_5b.setForeground(new java.awt.Color(123, 0, 0));
        Button_5b.setText("Ex_5b");
        Button_5b.setBorder(null);
        Button_5b.setBorderPainted(false);
        Button_5b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_5bActionPerformed(evt);
            }
        });
        getContentPane().add(Button_5b, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 120, 60));

        Button_6a.setBackground(new java.awt.Color(255, 255, 204));
        Button_6a.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Button_6a.setForeground(new java.awt.Color(123, 0, 0));
        Button_6a.setText("Ex_6a");
        Button_6a.setBorder(null);
        Button_6a.setBorderPainted(false);
        Button_6a.setMaximumSize(new java.awt.Dimension(65, 37));
        Button_6a.setMinimumSize(new java.awt.Dimension(65, 37));
        Button_6a.setPreferredSize(new java.awt.Dimension(65, 37));
        Button_6a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_6aActionPerformed(evt);
            }
        });
        getContentPane().add(Button_6a, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 120, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colocviu_final_Campean_Casiana/backgroundd.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));
        getContentPane().add(Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_6bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_6bActionPerformed
                                        
                                             
        try{
            ProiectBilet9.Instructiune("select AVG(cantitate) as avg from set_ingrediente where ingred_id=(select ingred_id from ingredient  where ingredient='usturoi')");
            StringBuilder rez6b=ProiectBilet9.rezultat6b("nume");
            Tabel.setText(rez6b.toString());
        }catch(SQLException exc){
            exc.printStackTrace();
        }
    
    
    }//GEN-LAST:event_Button_6bActionPerformed

    private void Button_3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_3aActionPerformed
         try{
            ProiectBilet9.Instructiune("select nume, descriere from Reteta where vegetariana='N' and timp_preparare between 60 and 120");
            StringBuilder rez3a=ProiectBilet9.rezultat3a("nume");
            Tabel.setText(rez3a.toString());
        }catch(SQLException exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_Button_3aActionPerformed

    private void Button_3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_3bActionPerformed
        try{
            ProiectBilet9.Instructiune("select * from set_ingrediente where comentarii is null");
            StringBuilder rez3b=ProiectBilet9.rezultat3b("ingred_id");
            Tabel.setText(rez3b.toString());
        }catch(SQLException exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_Button_3bActionPerformed

    private void Button_4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_4aActionPerformed
        try{
            ProiectBilet9.Instructiune("select  distinct  s1.reteta_id as reteta_id1 ,  s2.reteta_id as reteta_id2  from set_ingrediente s1 join set_ingrediente s2 on s1.reteta_id != s2.ingred_id where s1.ingred_id=1 and s2.ingred_id=1 and s1.reteta_id < s2.reteta_id");
            StringBuilder rez4a=ProiectBilet9.rezultat4a("reteta_id");
            Tabel.setText(rez4a.toString());
        }catch(SQLException exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_Button_4aActionPerformed

    private void Button_4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_4bActionPerformed
        try{
            ProiectBilet9.Instructiune("select nume, descriere from reteta r join set_ingrediente s on r.reteta_id=s.reteta_id join ingredient i on s.ingred_id=i.ingred_id where i.ingredient='ciuperci'");
            StringBuilder rez4b=ProiectBilet9.rezultat4b("nume");
            Tabel.setText(rez4b.toString());
        }catch(SQLException exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_Button_4bActionPerformed

    private void Button_5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_5aActionPerformed
       try{
            ProiectBilet9.Instructiune("select nume, descriere, timp_preparare from reteta where vegetariana='N' and timp_preparare < any(select timp_preparare  from reteta where vegetariana = 'D')");
            StringBuilder rez5a=ProiectBilet9.rezultat5a("nume");
            Tabel.setText(rez5a.toString());
        }catch(SQLException exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_Button_5aActionPerformed

    private void Button_5bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_5bActionPerformed
        try{
            ProiectBilet9.Instructiune("select ingredient from ingredient where ingred_id in (select ingred_id  from set_ingrediente where cantitate=(select max(cantitate)  from set_ingrediente))");
            StringBuilder rez5b=ProiectBilet9.rezultat5b("ingredient");
            Tabel.setText(rez5b.toString());
        }catch(SQLException exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_Button_5bActionPerformed

    private void Button_6aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_6aActionPerformed
         try{
            ProiectBilet9.Instructiune("select min(timp_preparare) as timp_preparare1, max(timp_preparare) as timp_preparare2 from reteta");
            StringBuilder rez6a=ProiectBilet9.rezultat6a("nume");
            Tabel.setText(rez6a.toString());
        }catch(SQLException exc){
            exc.printStackTrace();
        }
    }//GEN-LAST:event_Button_6aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException{
        new ProiectBilet9();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_3a;
    private javax.swing.JButton Button_3b;
    private javax.swing.JButton Button_4a;
    private javax.swing.JButton Button_4b;
    private javax.swing.JButton Button_5a;
    private javax.swing.JButton Button_5b;
    private javax.swing.JButton Button_6a;
    private javax.swing.JButton Button_6b;
    private javax.swing.JLabel Size;
    private javax.swing.JTextArea Tabel;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
